#!/bin/sh
# ~/.local/tools/upgradehook
yaycache="$(find $(yay -Pg | jq -r .buildDir) -maxdepth 1 -type d | awk '{ print "-c " $1 }' | tail -n +2)"
/usr/bin/paccache -rvk1 -c /var/cache/pacman/pkg $yaycache
